### ISSUE TITLE
Rewrite in Swift

### ISSUE THREAD

**Issue by sdegutis** [sdegutis/AppGrid#1]
Seriously. The code is just filled with craptastic redundancy due to Objective-C's primitivism. Swift would really rock here.

**Comment by UlasSAYGIN** [comment]
I can't se your app, how it is working can you show in video because i use shortcuts but nothing happens except preference screen comes on top of other windows

**Comment by sdegutis** [comment]
@UlasSAYGIN The preference screen is coming up on top of other windows because you need to enable accessibility for AppGrid to work. That's also why you're not seeing it work. And this isn't the right place to discuss this, please open a new issue if you have anything further to say about this. This issue is about an upcoming rewrite of AppGrid in the Swift programming language.
