### ISSUE TITLE
Add hotkeys and configuration options to README

### ISSUE THREAD

**Issue by paulmolluzzo** [sdegutis/AppGrid#2]
The README is a bit sparse. Adding the default configuration and how to adjust the configuration to the README would be good documentation for people using the app. Also, it helps describe how the app works so someone can decide to install it or not.

**Comment by sdegutis** [comment]
The configuration tool is a visual GUI which opens up on the first launch of the app, so new users shouldn't have difficulty finding it once they try the app. But it does make sense to re-add a screenshot of it to the README to visually explain to potential users how they can expect AppGrid to configure it.

**Comment by sdegutis** [comment]
Added it.

**Comment by paulmolluzzo** [comment]
Awesome! Thanks!
