### ISSUE TITLE
Allow changing margin setting

### ISSUE THREAD

**Issue by Edicatax** [sdegutis/AppGrid#4]
It'd be great if we could change the margin setting to have bigger/smaller gaps between windows.

**Comment by a1re1** [comment]
@Edicatax -- idk if you still want this, but I stumbled onto this app and wanted this feature. 

I went ahead and forked and added it since there hasn't been activity recently.

https://github.com/a1re1/AppGrid/releases/tag/1.0.4.1

**Comment by corrjo** [comment]
Closed with #6
