### ISSUE TITLE
Maintainer application

### ISSUE THREAD

**Issue by gingerbeardman** [sdegutis/AppGrid#5]
I'll do it 👍

I guess you took a job where they don't allow you to have your own apps? 🍎

We'd have to discuss your other repos

Thanks and all the best

**Comment by sdegutis** [comment]
Ok. I’ll transfer it as soon as Github helps me back into my Github account (got locked out, sent an email 1 or 2 days ago, should hear back any time now). Any others you want to maintain, just let me know.

**Comment by sdegutis** [comment]
Can you change the license name too, to take my name out?

**Comment by gingerbeardman** [comment]
Sorry just got round to looking at this
